name: myghpage
version: 0.0.1
description: this may not go anywhere
author: todd beckman
dependencies:
  browser: ^0.10.0
  uuid: ^0.5.3
  over_react: any
  w_module: ^1.0.0

dev_dependencies:
  test: ^0.12.20

transformers:
  - over_react
  - $dart2js
